spring.application.name=crash_course
server.port=8085
spring.data.mongodb.uri=mongodb+srv://anauriasmachado_db_user:{password}@user.6srxd3l.mongodb.net/house_testing?retryWrites=true&w=majority&appName=User
